### ISSUE TITLE
Add Podcast - Search - Change Region is not working

### ISSUE THREAD

**Issue by oldman63** [Podcast-Republic/PodcastRepublic-iOS#10]
App default language is English
Country/Region: United States

Changing region, Select Hungary (or other), Not Working

Approve Country button is missing!?

**Comment by gemiren** [comment]
Do you mean you can not change the country/region or the top charts are not updated after changing country/region?

**Comment by oldman63** [comment]
Yes, I cannot change it.

**Comment by gemiren** [comment]
> Yes, I cannot change it.

It seems I was able to change it. I'll try harder to reproduce it. Thanks.

**Comment by oldman63** [comment]
https://user-images.githubusercontent.com/3171626/228737419-abcea0b6-820a-47e9-97dd-cbce38c0fb7e.mp4

**Comment by gemiren** [comment]
Thanks for the video. I was able to reproduce the bug following the steps. Will fix it asap.

Currently, you can go to app Settings > Podcasts to change the country/region. It works there.
