### ISSUE TITLE
Missing texts in English language source

### ISSUE THREAD

**Issue by oldman63** [Podcast-Republic/PodcastRepublic-iOS#11]
Missing texts marked in red

![IMG_0472-2](https://user-images.githubusercontent.com/3171626/228604879-45d660b1-3abc-49cf-a072-fe6623ab85fd.png)
![IMG_0474-2](https://user-images.githubusercontent.com/3171626/228604884-615ca72d-49f3-4126-8cda-e4f96e09771f.png)
![IMG_0475-2](https://user-images.githubusercontent.com/3171626/228604886-7bada35d-1316-4621-acf9-c680cd3d91dd.png)
![IMG_0476-2](https://user-images.githubusercontent.com/3171626/228604890-d19b70bf-bad1-4348-b223-bd19af5cc1b1.png)
![IMG_0477-2](https://user-images.githubusercontent.com/3171626/228604893-201e900c-db33-4d1a-87b5-04c4f972204f.png)
![IMG_0479-2](https://user-images.githubusercontent.com/3171626/228604897-19c16360-af42-44c6-ad5c-5ba1d03caeef.png)

**Comment by oldman63** [comment]
v23.3.1.330

![IMG_0512-2](https://user-images.githubusercontent.com/3171626/229120159-73214d53-46f9-44d0-b4da-d6013a6c2a92.png)

**Comment by oldman63** [comment]
![IMG_0515-3](https://user-images.githubusercontent.com/3171626/229162236-bfb9338c-bf59-4d26-8294-f416bbe44b64.png)

**Comment by gemiren** [comment]
Fixed. Thanks.

**Comment by oldman63** [comment]
Fix is ok this texts:

Select your preferred language
3 lines
There are no episodes
All -Unplayed - Played
After current episode ends
Downloading.

This texts is waiting for fixing:

Clear cache - Cache size
