### ISSUE TITLE
Podcast exported to: [Output]

### ISSUE THREAD

**Issue by oldman63** [Podcast-Republic/PodcastRepublic-iOS#14]
**Downloads/Export download**

Where is it exported to?

![IMG_0523](https://user-images.githubusercontent.com/3171626/229339573-a039e8b0-2a47-48ef-91f9-cf2341e2a13e.PNG)
![IMG_0522-2](https://user-images.githubusercontent.com/3171626/229339580-dd174c02-2fb4-43a9-9346-dc9fa20452e5.png)

**Comment by gemiren** [comment]
The Output directory is under this app's root directory. You can open the Files app, navigate to this app to find it.

**Comment by oldman63** [comment]
Thank you!

This is a proposed new topic for the application FAQ!
