### ISSUE TITLE
Android/iOS localisation disorder

### ISSUE THREAD

**Issue by oldman63** [Podcast-Republic/PodcastRepublic-iOS#15]
**English text:** Follow system's dark theme setup

**Actual text in values-hu/strings.xml:**
<string name="follow_os_systems_dark_theme_setup">Az Android rendszer sötét témára vonatkozó beállításának követése</string>

**Actual text under iOS:** Az rendszer sötét témára vonatkozó beállításának követése

**Correct text under iOS:** A rendszer sötét témára vonatkozó beállításának követése
or
Az iOS rendszer sötét témára vonatkozó beállításának követése

![IMG_0524-2](https://user-images.githubusercontent.com/3171626/229340038-78ce0690-cb05-4973-afca-0d10bb481372.png)
![IMG_0519-2](https://user-images.githubusercontent.com/3171626/229340040-2d71d6d8-b390-4602-989e-0caf8a8be909.png)

**Comment by gemiren** [comment]
Fixed. Thanks.

**Comment by oldman63** [comment]
Thx, fix is ok.
