### ISSUE TITLE
English text

### ISSUE THREAD

**Issue by oldman63** [Podcast-Republic/PodcastRepublic-iOS#17]
v23.3.1 (402)

Hungarian language - English text

![IMG_0545](https://user-images.githubusercontent.com/3171626/229461367-dc9baea9-1e19-44a8-8dd8-3ab3c9aaf993.PNG)

**Comment by oldman63** [comment]
Manage tags

![IMG_0552-2](https://user-images.githubusercontent.com/3171626/229473231-d509ddf5-cab2-4d7a-be54-9c6a0658a9c1.png)

**Comment by oldman63** [comment]
Share

![IMG_0553-2](https://user-images.githubusercontent.com/3171626/229496274-657349fb-a574-4b4d-ab11-25844788e3fa.png)

**Comment by gemiren** [comment]
Fixed in the latest beta version. Thanks.

**Comment by oldman63** [comment]
Manage tags and Share text is OK.

Share is problematic!

Text is shifted left...

![IMG_0558-2](https://user-images.githubusercontent.com/3171626/229701284-62b7f805-3b7f-416f-9f13-4a13d9b151f3.png)

**Comment by gemiren** [comment]
Nice catch. Fixed now.
