### ISSUE TITLE
Bug: crashing podcast app when opening subscription

### ISSUE THREAD

**Issue by Penthious** [Podcast-Republic/PodcastRepublic-iOS#2]
# What

When opening the app, after syncing my account, i click a subscription and the app crashes before loading any of the episodes.

Some subscriptions work but others crash on click of subscription, a few for me are:
* ars paradoxical
* lore
*  Margaret's garden

**Comment by gemiren** [comment]
Should be fixed in today's beta update. Please update your app to the latest beta and let me know if the issue is still there. Thanks.

**Comment by Penthious** [comment]
This is now fixed from the latest update. Thank you
