### ISSUE TITLE
Missing translation - "Don't show it again"

### ISSUE THREAD

**Issue by oldman63** [Podcast-Republic/PodcastRepublic-iOS#23]
iOS v23.7.3.731

After reorder "Up Next" list:

string name="don_t_show_it_again">Legközelebb ne mutassa.

???

![IMG_0369](https://github.com/Podcast-Republic/PodcastRepublic-iOS/assets/3171626/be631d64-8544-4d31-aab6-6cd14a6723d0)

**Comment by oldman63** [comment]
Sorry, after upgrading to v23.8.1.807 the whole message does not appear, so I can't recheck the problem.

**Comment by gemiren** [comment]
Will fix this in the next update. Thanks!
