### ISSUE TITLE
User Interface/Text size is not working

### ISSUE THREAD

**Issue by oldman63** [Podcast-Republic/PodcastRepublic-iOS#25]
iOS 17.1 XS Max
PR v23.10.3.1027

When I change the setting, neither the sample text nor the UI changes.

![IMG_0507-2](https://github.com/Podcast-Republic/PodcastRepublic-iOS/assets/3171626/1c10c08e-d774-4ffd-b53a-3db204f0a36a)
![IMG_0508-2](https://github.com/Podcast-Republic/PodcastRepublic-iOS/assets/3171626/1a832dae-7db1-485c-a75d-8570f731b037)

**Comment by gemiren** [comment]
Currently, on iOS, the text size setting is only applicable to the episode description in the Now playing or episode info pages.

**Comment by oldman63** [comment]
ok, sorry

**Comment by gemiren** [comment]
You are welcome. The iOS, or more precisely the SwiftUI, doesn't allow an easy way to adjust the text size app-wide like the Android.
