### ISSUE TITLE
Discover is crashed

### ISSUE THREAD

**Issue by oldman63** [Podcast-Republic/PodcastRepublic-iOS#27]
Open Main menu
Select Discover
Select Featured -> More
Back
Select Featured -> More again

Display content is crashes

Podcast Republic beta 24.2.1  (240213)
iOS 17.4 public beta (This also happens with iOS 17.3.1)
iPhone 12

https://github.com/Podcast-Republic/PodcastRepublic-iOS/assets/3171626/5b144634-1b7d-456a-970b-227e64b38e28

**Comment by gemiren** [comment]
Thanks very much for the detailed bug report. This bug is now fixed in the latest beta update.

**Comment by oldman63** [comment]
Thanks

**Comment by oldman63** [comment]
Under new beta is working good
