### ISSUE TITLE
Edit Podcast URL windows is to small

### ISSUE THREAD

**Issue by oldman63** [Podcast-Republic/PodcastRepublic-iOS#28]
The Podcast Editor window size too small

iOS 17.4 public beta, iPhone 12, 24.2.1.240217

![IMG_0075](https://github.com/Podcast-Republic/PodcastRepublic-iOS/assets/3171626/d197454e-5efb-448f-8b58-080220fddd30)

**Comment by gemiren** [comment]
Will fix that. Thanks.

**Comment by oldman63** [comment]
v24.2.1.240219

Fixing is OK, thanks
