### ISSUE TITLE
Search Podcast function is crashed

### ISSUE THREAD

**Issue by oldman63** [Podcast-Republic/PodcastRepublic-iOS#29]
Push + icon (add podcast)
Search podcasts
Write Heti
Push Return
App is crashed

iOS 17.4 public beta, iPhone 12, 24.2.1.240217

**Comment by gemiren** [comment]
Can you reproduce this issue? I tried many times with different devices but still couldn't reproduce it. Thanks.

**Comment by oldman63** [comment]
See attached video


https://github.com/Podcast-Republic/PodcastRepublic-iOS/assets/3171626/2cd9651f-5446-49cd-a888-4b261e40b7c3

**Comment by gemiren** [comment]
> See attached video
> 
> 
> 
> 
> 
> https://github.com/Podcast-Republic/PodcastRepublic-iOS/assets/3171626/2cd9651f-5446-49cd-a888-4b261e40b7c3
> 
> 
> 
> 

Thanks very much for the screen recording. Please update your app to the latest beta and let me know if the crash is still there.

**Comment by oldman63** [comment]
Sorry, after update last beta, the crash is still there.

**Comment by gemiren** [comment]
> Sorry, after update last beta, the crash is still there.

Does it still crash in today's update? What's weird is that I'm still not able to reproduce this crash on my iPhone. Thanks.

**Comment by oldman63** [comment]
Hello, good news, the problem is solved, thank you!

**Comment by gemiren** [comment]
Awesome. Thanks very much for helping fixing this crash!
