### ISSUE TITLE
Not translated time strings

### ISSUE THREAD

**Issue by oldman63** [Podcast-Republic/PodcastRepublic-iOS#30]
See attached screenshot:

H - Hour
M - Minute
S - Sec

![IMG_0136-2](https://github.com/Podcast-Republic/PodcastRepublic-iOS/assets/3171626/1a6086d3-adac-4b85-9f5f-283f6cb04731)

**Comment by gemiren** [comment]
Nice catch. Fixed in today's update. Thanks.

**Comment by oldman63** [comment]
Next catch

Episode Filter

![IMG_0148-2](https://github.com/Podcast-Republic/PodcastRepublic-iOS/assets/3171626/c27e931c-6f2a-43a7-9a13-a41d2cc28ae8)

**Comment by gemiren** [comment]
The string is already in the language file at line 878:
<string name="short_time_unit_format_minute">Min</string>

Can you translate it? Thanks.

**Comment by oldman63** [comment]
Opss... I will translate it immediately.
