### ISSUE TITLE
Missing Translation

### ISSUE THREAD

**Issue by oldman63** [Podcast-Republic/PodcastRepublic-iOS#35]
Below two screenshots...

Android 2021.11.29 and iOS 2024.04.10

Please add the missing "time unit" to the (iOS) source for translation

Android
![2021 11 29-2](https://github.com/Podcast-Republic/PodcastRepublic-iOS/assets/3171626/4d89f082-28d1-45e9-a549-1ad629348b8e)

iOS
![2024 04 10-2](https://github.com/Podcast-Republic/PodcastRepublic-iOS/assets/3171626/03d3251c-f341-476e-af26-ede83158354d)

**Comment by gemiren** [comment]
Fixed in the latest beta version. Thanks!

**Comment by oldman63** [comment]
Ok, thx
