### ISSUE TITLE
Problem on History page

### ISSUE THREAD

**Issue by oldman63** [Podcast-Republic/PodcastRepublic-iOS#36]
Today I started listening to the Podcast episode below (S1E145...) currently playing.

Meanwhile, opening the History page and then turning on the "Show played date" option, the data displayed is incorrect.
I listened to the previous episode (S4E193) today. The Podcast Addict says it was a month ago. :-)

I think it is not the play date that is displayed, but the Publish date. 

Plus: The "Show played date" option has no on and off state, in both cases the same thing is displayed in the menu (Show played date).

![IMG_0182](https://github.com/Podcast-Republic/PodcastRepublic-iOS/assets/3171626/e7cfa625-d849-4ea3-8340-4e71456ea6f2)

![IMG_0183](https://github.com/Podcast-Republic/PodcastRepublic-iOS/assets/3171626/854a1bb7-13b3-4318-b7bb-a569ea86535d)

**Comment by gemiren** [comment]
Nice catch. Will fix that in the next update. Thanks!

**Comment by oldman63** [comment]
Thank you.

**Comment by oldman63** [comment]
Fixed

**Comment by oldman63** [comment]
Sorry, but where are these "time strings" found in translation sources?

day ago
week ago
month ago

**Comment by gemiren** [comment]
> Sorry, but where are these "time strings" found in translation sources?
> 
> 
> 
> day ago
> 
> week ago
> 
> month ago
> 
> 

They're iOS system provided localized time/date displays.

**Comment by oldman63** [comment]
Thx
