### ISSUE TITLE
Import RSS feed from iCloud is not working

### ISSUE THREAD

**Issue by oldman63** [Podcast-Republic/PodcastRepublic-iOS#9]
Select the "Import from OPML file" menu item
The Files application opens
iCloud opens
All files are "unselectable" and therefore cannot be imported

Why?

Adding the rss feed after Search, works fine

iOS 16.4, iPhone XS Max, 23.3.1.324 version

**Comment by gemiren** [comment]
Save the opml file to your device first. That should work.

**Comment by oldman63** [comment]
What is the way to do this on iOS?

**Comment by gemiren** [comment]
> What is the way to do this on iOS?

Open the system's Files app. You can move the opml file for the icloud to anywhere on your device locally.

**Comment by oldman63** [comment]
I understand, but it still does not work. The file(s) is unselectable.
See the video below.

https://user-images.githubusercontent.com/3171626/228735908-0028b3f0-a869-4a47-9d49-8b61753b8988.mp4

iOS 16.4

**Comment by gemiren** [comment]
![image](https://user-images.githubusercontent.com/7810771/228737727-bffadf04-cb2a-47c2-834e-0421ef7c458e.jpeg)

Not sure why but long pressing the opml gives more options on my phone. Maybe yours is a shortcut instead of the actual file?

**Comment by oldman63** [comment]
If I launch the Files app directly, I get the same thing.
However, if it's called from under Podcast Republic, it's not.

**Comment by oldman63** [comment]
https://user-images.githubusercontent.com/3171626/228746238-f333305c-4a24-4d44-becb-86b0514c5503.mp4

**Comment by oldman63** [comment]
Any idea for importing the OPML from iCloud?

Anything I copy anywhere in the Files app, all files are inactive when viewed from under Podcast Republic.

**Comment by gemiren** [comment]
Can you try downloading the opml file to your computer and then put it on your phone again? Hopefully that works.

**Comment by oldman63** [comment]
I have tried all variations, in the Files application all OPML files are inactive. Whether the file is on iCloud or on the device.

**Comment by gemiren** [comment]
Can you send the opml file to tech@podcastrepublic.net ? I'll see if I can reproduce it. Thanks.

**Comment by oldman63** [comment]
By renaming the OPML file extension to XML, the import was successful.

Could this be an iOS bug?
